export { EconomicCrisisOverviewSection, KeyCrisesSection, UAERelevanceSection } from './EconomicCrisisOverviewSection'
export { DubaiCrisis2009Section, DebtStructureSection, PropertyMarketSection, NakheelDubaiWorldSection } from './DubaiCrisis2009Section'
export { IranWar2026Section, ExchangeClosuresSection, SectorImpactSection } from './IranWar2026Section'
export { AbraajSection, NMCSection, OtherFraudsSection } from './CorporateFraudsSection'
export { BankingSectorSection, SovereignDebtSection } from './BankingSectorSection'
export { CrisisTimelineSection } from './CrisisTimelineSection'
export { default } from './EconomicCrisisOverviewSection'